ZO_CreateStringId("SI_BINDING_NAME_FCOCS_ADDON_SETTINGS_MENU", "AddOns")
ZO_CreateStringId("SI_BINDING_NAME_FCOCS_MAP_PLAYER_PIN_PING_PONG", "Map: Player pin ping pong")
ZO_CreateStringId("SI_BINDING_NAME_FCOCS_TOGGLE_SETTINGS_COMPASS_QUEST_GIVERS", "Settings: Compass quest givers")